lee:
  tcpPort: 9000
  webSocketPort: 19000
  bossThreadSize: 1 # 线程组
  workThreadSize: 8 # 工作线程

  redis:
    mode: single # 单机模式：single 哨兵模式：sentinel 集群模式：cluster
    database: 0
    password:
    timeout: 3000 # 超时时间
    poolMinIdle: 8 #最小空闲数
    poolConnTimeout: 3000 # 连接超时时间(毫秒)
    poolSize: 10 # 连接池大小
    single: #redis单机配置
      address: 192.168.56.101:6379