spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:192.168.1.132}:${MYSQL_PORT:3306}/imooc-im-core?serverTimezone=UTC&useSSL=false&characterEncoding=UTF8
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASS:root1234}

  application:
    name: im-core

# logger 配置
logging:
  config: classpath:logback-spring.xml

server:
  port: 8000

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/*.xml
  global-config:
    db-config:
      update-strategy: NOT_EMPTY

#mybatis:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# Apache
httpclient:
  maxTotal: 100
  defaultMaxPerRoute: 50 # 默认每条路线的最大值
  connectTimeout: 2000 # 连接超时
  connectionRequestTimeout: 2000 # 连接请求超时
  socketTimeout: 5000 # 套接字超时
  staleConnectionCheckEnabled: true
  callbackUrl: http://127.0.0.1:8000/callback
  modifyUserAfterCallback: false # 用户资料变更之后回调开关

appConfig:
  zkAddr: 192.168.56.101:2181 # zk连接地址
  zkConnectTimeOut: 50000 #zk超时时间
  imRouteWay: 1 # 路由策略1轮训 2随机 3hash
  consistentHashWay: 1 # 如果选用一致性hash的话具体hash算法 1 TreeMap 2 自定义Map
  callbackUrl: http://127.0.0.1:8000/callback
  modifyUserAfterCallback: false # 用户资料变更之后回调开关
  addFriendAfterCallback: false # 添加好友之后回调开关
  addFriendBeforeCallback: false # 添加好友之前回调开关
  modifyFriendAfterCallback: false # 修改好友之后回调开关
  deleteFriendAfterCallback: false # 删除好友之后回调开关
  addFriendShipBlackAfterCallback: false #添加黑名单之后回调开关
  deleteFriendShipBlackAfterCallback: false #删除黑名单之后回调开关
  createGroupAfterCallback: false # 创建群聊之后回调开关
  modifyGroupAfterCallback: false # 修改群聊之后回调开关
  destroyGroupAfterCallback: false # 解散群聊之后回调开关
  deleteGroupMemberAfterCallback: false # 删除群成员之后回调
  addGroupMemberAfterCallback: false # 拉人入群之后回调
  addGroupMemberBeforeCallback: false # 拉人入群之前回调