spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:192.168.1.132}:${MYSQL_PORT:3306}/imooc-im-core?serverTimezone=UTC&useSSL=false&characterEncoding=UTF8
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASS:root1234}

  redis:
    host: 192.168.56.101
    port: 6379
    jedis:
      pool:
        max-active: 100
        max-idle: 100
        max-wait: 1000
        min-idle: 10

  rabbitmq:
    host: 192.168.56.101
    port: 5672
    addresses: 192.168.56.101
    username: guest
    password: guest
    #    virtual-host:
    listener:
      simple:
        concurrency: 5
        max-concurrency: 10
        acknowledge-mode: MANUAL
        prefetch: 1
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true
    cache:
      connection:
        mode: channel
      channel:
        size: 36
        checkout-timeout: 0

# logger 配置
logging:
  config: classpath:logback-spring.xml

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/*.xml
  global-config:
    db-config:
      update-strategy: NOT_EMPTY

#mybatis:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# Apache
httpclient:
  maxTotal: 100
  defaultMaxPerRoute: 50 # 默认每条路线的最大值
  connectTimeout: 2000 # 连接超时
  connectionRequestTimeout: 2000 # 连接请求超时
  socketTimeout: 5000 # 套接字超时
  staleConnectionCheckEnabled: true